CREATE TABLE "ADDRESS"
(
	"ID" BIGINT NOT NULL,
	"COUNTRY" VARCHAR(255) NOT NULL,
	"CITY" VARCHAR(255) NOT NULL,
	"STREET" VARCHAR(255) NOT NULL,
	"POST_CODE" VARCHAR(15) NOT NULL,
	CONSTRAINT "ADDRESS_PKEY" PRIMARY KEY ("ID")
)

CREATE TABLE "PROJECT"
(
	"ID" BIGINT NOT NULL,
	"TITLE" VARCHAR(255) NOT NULL,
	CONSTRAINT "PROJECT_PKEY" PRIMARY KEY ("ID")
)

CREATE TABLE "EMPLOYEE"
(
	"ID" BIGINT NOT NULL,
	"FIRST_NAME" VARCHAR(255) NOT NULL,
	"LAST_NAME" VARCHAR(255) NOT NULL,
	"BIRTHDATE" DATE NOT NULL,
	"ADDRESS_ID" BIGINT NOT NULL,
	CONSTRAINT "EMPLOYEE_PKEY" PRIMARY KEY ("ID"),
	CONSTRAINT "EMPLOYEE_FKEY" FOREIGN KEY ("ID") REFERENCES "ADDRESS" ("ID")
)

CREATE TABLE "EMPL_PROJ"
(
	"EMPLOYEE_ID" BIGINT NOT NULL,
	"PROJECT_ID" BIGINT NOT NULL,
	CONSTRAINT "EMPL_PROJ_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEE" ("ID"),
	CONSTRAINT "EMPL_PROJ_PROJECT_ID_fkey" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT" ("ID")
)